version: 2
updates:
  # Mantener las dependencias de npm actualizadas
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "npm dependencies"
      - "dependencies"
      
  # Mantener las acciones de GitHub actualizadas
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependencies"

